# Generated by Django 3.0.3 on 2020-06-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
